src/types/environment.d.ts
=> feat: Add BASE_URL to environment variable types

src/components/emails/PasswordChanged.tsx, src/server/api/emails/actions.tsx
Added the PasswordChanged component and filled out the sending function.
Issue #9: Create a Password Changed Email
=> feat: Made PasswordChanged Component

src/app/api/auth/[...nextauth]/options.ts, src/app/dashboard/page.tsx, src/app/enrollment-form/page.tsx, src/app/forgot-password/[token]/page.tsx, src/app/page.tsx, src/app/test/account/page.tsx, src/app/test/client/page.tsx, src/app/test/server/page.tsx, src/components/ForgotPassword/ForgotPasswordForm.tsx, src/components/ForgotPassword/ResetPasswordForm.tsx, src/components/Header/index.tsx, src/components/LoginForm/index.tsx, src/server/api/password-reset-tokens/mutations.tsx, src/server/api/password-reset-tokens/queries.tsx, src/server/api/program-enrollments/mutations.ts, src/server/api/program-enrollments/queries.ts, src/server/api/users/mutations.ts, src/server/api/users/queries.ts, src/server/api/users/secure-mutations.ts, src/types/ApiResponse.ts, src/utils/authenticateServerFunction.ts, src/utils/handleMongooseError.ts
=> feat: Rework API responses and extract header into layout

.github/workflows/pr.yml, src/app/dashboard/admin/page.tsx, src/app/dashboard/client/page.tsx, src/app/settings/admin/page.tsx, src/app/settings/client/page.tsx, src/app/settings/page.tsx, src/components/Settings/SignOutButton.tsx
=> feat: Center dashboards and add settings for live demo

src/components/Header/index.tsx, src/components/Settings/SignOutButton.tsx, src/components/emails/ResetPasswordEmail.tsx, src/components/emails/WelcomeEmail.tsx, src/server/api/program-enrollments/mutations.ts, src/server/api/program-enrollments/queries.ts, src/styles/theme.ts
=> feat: Add sign out, colors, and approve server action

src/components/emails/RejectionEmail.tsx, src/server/api/emails/actions.tsx
Created the rejection email component.
Issue #39: Reject Email
=> feat: Created rejection email

.vscode/launch.json, src/app/test/client/page.tsx, src/server/api/users/mutations.ts, src/utils/constants/apiErrors.ts
=> feat: Create change password server action

src/components/EnrollmentForm/ProgramSpecificQuestions/HealthyHabitsProgramSpecificQuestions.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/RigsWithoutCigsProgramSpecificQuestions.tsx
=> feat: Label certain form text fields for mobile view

src/components/EnrollmentForm/ProgramSpecificQuestions/HealthyHabitsProgramSpecificQuestions.tsx, src/types/EnrollmentForm/ProgramSpecificQuestionsSection.ts
=> feat: Hotfix form submission

src/app/enrollment-form/disqualified/page.tsx, src/app/enrollment-form/submitted/page.tsx, src/app/not-found.tsx, src/components/EnrollmentForm/DisqualifiedFormSection.tsx, src/components/EnrollmentForm/GeneralInformationFormSection.tsx, src/components/EnrollmentForm/ProgramSelectionFormSection.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/HealthyHabitsProgramSpecificQuestions.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/RigsWithoutCigsProgramSpecificQuestions.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/VaccineVoucherProgramSpecificQuestions.tsx, src/components/EnrollmentForm/QualifyingQuestionsFormSection.tsx, src/components/EnrollmentForm/SubmittedFormSection.tsx, src/components/NotFound/index.tsx, src/providers/EnrollmentFormProvider.tsx
=> feat: Add better form headings

src/server/api/program-enrollments/mutations.ts
- Added reject program enrollment server action
- #38
=> feat: Added reject program enrollment server action.

src/components/LoginForm/index.tsx, src/components/Settings/SignOutButton.tsx
Sometimes when you log in it'll ask you to log in again because it thought you weren't authed. Seems like a race condition.
Also when you signed out it didn't take you back to homepage so this fixes that
=> fix: Fix wrong redirection on sign in and sign out

src/components/AdminDashboard/PendingApplicationDashboard/AcceptPendingApplicationButton/index.tsx, src/components/AdminDashboard/PendingApplicationDashboard/RejectPendingApplicationButton/index.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/server/api/program-enrollments/mutations.ts
=> feat: Add functionality to accept and reject buttons

.eslintrc.cjs, src/app/dashboard/admin/page.tsx, src/components/AdminDashboard/PendingApplicationDashboard/AcceptPendingApplicationButton/index.tsx, src/components/AdminDashboard/PendingApplicationDashboard/RejectPendingApplicationButton/index.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx
=> feat: Make form more responsive and add more TS linting

pnpm-lock.yaml, src/app/dashboard/admin/applications/page.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx
Add a search filter to the pending application table along with modifying table styling
#59 
#35 
Type into the new search bar and the table should automatically update
=> feat: Add search filter to pending application table

src/app/change-password/page.tsx, src/components/ChangePassword/ChangePasswordForm.tsx, src/components/EnrollmentForm/DisqualifiedFormSection.tsx, src/components/EnrollmentForm/SubmittedFormSection.tsx, src/components/ForgotPassword/InvalidPasswordResetToken.tsx, src/components/NotFound/index.tsx, src/components/Settings/AdminSettings.tsx, src/components/Settings/ChangePasswordButton.tsx, src/components/Settings/ClientSettings.tsx, src/components/VerifyEmail/InvalidEmailVerificationToken.tsx, src/components/VerifyEmail/VerifyEmail.tsx, src/components/VerifyEmail/VerifyEmailSuccess.tsx, src/server/api/users/private-mutations.ts, src/server/api/users/public-mutations.ts
Create the change password page
#13 
1) Login into your account
2) go /change-password
3) change your password (don't forget to check the validations)
4) sign out of your account
5) attempt to log in into your account with both the old and new password
=> feat: Implement change password form

src/app/dashboard/client/page.tsx, src/components/ClientDashboard/EnrolledProgramsSelectionScreen.tsx, src/components/EnrollmentForm/DisqualifiedFormSection.tsx
added a component called EnrolledProgramsSelectionScreen that takes in an array of program enrollments. It displays them as boxes to be clicked on
NA
create a new test account, manually change the program request status to accepted in the db, then login with said account and view the dashboard page. test with multiple programs and with no programs accepted
=> feat: canvas style view of program enrollments

src/app/dashboard/client/page.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/components/ClientDashboard/EnrolledProgramsSelectionScreen.tsx, src/server/api/program-enrollments/queries.ts
=> feat: Make client dashboard cards blue

src/app/test/client/page.tsx, src/components/ProgramSectionDropdown/index.tsx
Created the dropdown component in components/ProgramSectionDropdown. 
#61: Add Dropdown for Client view
I used the `/test/client`page to test it since I wasn't sure where /dashboard/client/healthy-habits page.tsx was. To test it:
- Import: import ProgramSectionDropdown from "@/components/ProgramSectionDropdown";
- Add component: < ProgramSectionDropdown />
=> feat: Added dropdown for client view

src/components/AdminDashboard/PendingApplicationDashboard/PendingApplicationInfoModal/ProgramSpecificResponses/HealthyHabitsAndDiabetesPreventionResponses.tsx, src/components/EnrollmentForm/GeneralInformationFormSection.tsx, src/components/EnrollmentForm/ProgramSelectionFormSection.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/HealthyHabitsProgramSpecificQuestions.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx, src/components/EnrollmentForm/QualifyingQuestionsFormSection.tsx, src/providers/EnrollmentFormProvider.tsx, src/server/models/EnrollmentForm.ts, src/types/EnrollmentForm/GeneralInformationSection.ts, src/types/EnrollmentForm/ProgramSpecificQuestionsSection.ts, src/types/OldEnrollmentForm.ts, src/utils/calculateBmi.ts, src/utils/constants/formDefaultValues.ts, src/utils/getBmiClassification.ts
=> feat: Split up BMI into heightFeet and heightInches

src/components/EnrollmentForm/DisqualifiedFormSection.tsx, src/components/EnrollmentForm/GeneralInformationFormSection.tsx, src/components/EnrollmentForm/ProgramSelectionFormSection.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/GetPreventativeScreeningsProgramSpecificQuestions.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx, src/components/EnrollmentForm/QualifyingQuestionsFormSection.tsx, src/utils/calculateAge.ts, src/utils/getBmiClassification.ts
=> feat: Add disqualification and conditional hiding of fields to form

src/server/api/emails/helpers.ts
=> feat: Update mail options to prevent ending up in spam

next.config.mjs, src/app/api/auth/[...nextauth]/options.ts, src/app/test/client/page.tsx, src/app/test/server/page.tsx, src/components/Header/index.tsx, src/components/LoginForm/index.tsx, src/components/VerifyEmail/VerifyEmailSuccess.tsx
=> feat: Fix sign in callbackUrl bug and prevent signOut when verifying email

src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/WeightLineChart.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/index.tsx, src/components/Header/index.tsx, src/server/api/emails/helpers.ts
=> feat: Fix settings button not showing up on sign in

.github/workflows/pr.yml, README.md, src/app/api/users/actions/create-admin-account/route.ts, src/types/environment.d.ts
=> feat: Rename ADMIN_CREATION_KEY to API_KEY

src/components/ClientDashboard/HealthyHabits/HealthyHabitsTracking.tsx
=> feat: Use local time when setting submitted date default

src/components/AdminDashboard/PendingApplicationDashboard/PendingApplicationInfoModal/index.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/HealthyHabitsTrackingFormList/HealthyHabitsTrackingFormModal.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsTracking.tsx
=> feat: Use local time and add submitted date to enrollment form modal

src/app/dashboard/admin/programs/healthy-habits/page.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsClientDashboard.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsMetrics.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/index.tsx, src/server/api/program-enrollments/queries.ts
Add a dashboard that allows admins to check if Healthy Habit users completed the tracking form for the week
#94 
1. Go to `dashboard/admin/programs/healthy-habits` as an admin
2. Check if there is a "x" by your account
3. Log into your client account 
4. Complete a healthy habit tracking form
5. Go back to `dashboard/admin/programs/healthy-habits` as an admin
6. Verify that your account has a check indicating that you completed a tracking form this week
=> feat: Implement Admin Healthy Habit Dashboard

src/components/emails/EmailVerificationEmail.tsx, src/components/emails/PasswordChangedEmail.tsx, src/components/emails/RejectionEmail.tsx, src/components/emails/ResetPasswordEmail.tsx, src/components/emails/SCFEmail.tsx, src/components/emails/WelcomeEmail.tsx, src/components/emails/ZoomReminderEmail.tsx
=> feat: Extract email template into separate component

src/app/settings/client/page.tsx, src/components/Settings/AdminSettings.tsx, src/components/Settings/ClientSettings.tsx
Added accepted programs list in client settings. Not the prettiest layout though.
#93 
Make a mock client account, accept the client's program applications from an admin account, then check client settings using the same client account.
=> feat: render programs enrolled in client settings

src/app/dashboard/client/diabetes-prevention/page.tsx, src/app/dashboard/client/get-preventative-screenings/page.tsx, src/app/dashboard/client/rigs-without-cigs/page.tsx, src/app/dashboard/client/vaccine-voucher/page.tsx, src/utils/isEnrolledInProgram.ts
=> feat: Prevent clients from accessing programs they are not enrolled in

src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/ModularLineChart.tsx
=> feat: Refactor line chart

src/app/dashboard/admin/layout.tsx, src/app/dashboard/admin/notifications/page.tsx, src/components/AdminDashboard/NotificationsDashboard/RecurringMeetings.tsx, src/components/AdminDashboard/NotificationsDashboard/UrgentMeetingRequests.tsx, src/components/AdminDashboard/NotificationsDashboard/index.tsx, src/components/AdminDashboard/Sidebar/index.tsx, src/server/api/urgent-meeting-requests/private-mutations.ts, src/server/api/urgent-meeting-requests/public-mutations.ts, src/server/api/urgent-meeting-requests/queries.ts
=> feat: Add table to view urgent meeting requests

src/app/api/users/actions/create-admin-account/route.ts, src/components/AdminDashboard/ClientManagementDashboard/index.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsClientDashboard.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/VaccineVoucherProgramSpecificQuestions.tsx, src/server/api/enrollment-forms/public-mutations.ts, src/server/api/users/private-mutations.ts, src/server/models/User.ts, src/types/EnrollmentForm/GeneralInformationSection.ts, src/types/EnrollmentForm/ProgramSpecificQuestionsSection.ts, src/types/User.ts
Add phone number to user and add Walmart and Sam's Club to vaccine form
#125 
Insure you can submit a enrollment form with Walmart and Sam's Club as vaccine provider
=> refactor: Add phone number to user

src/utils/prizeFunction.ts, src/utils/timeUntilNextPrize.ts
Added prize function in utils.
#124: Rigs without cigs prize utility function
I tested it on test/server, here's the code to test:
(let me know if you want me to send the test code somewhere else because the full code isn't showing up)
import { Box, Typography } from "@mui/material";
import { ReactNode } from "react";
import dayjs from "dayjs";
import { timeUntilNextPrize } from "@/utils/prizeFunction";
export default function ServerComponentTestPage(): ReactNode {
const programAcceptanceDate = dayjs("2025-02-09");
const prizeTimes = timeUntilNextPrize(programAcceptanceDate);
return (
<Box
sx={{
height: "100vh",
width: "100vw",
display: "flex",
justifyContent: "center",
alignItems: "center",
flexDirection: "column", // Stack elements vertically
}}
>
<Typography variant="h4">Server …
=> feat: Added Rigs Without Cigs Prize Utility Function

src/app/dashboard/admin/notifications/page.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsClientDashboard.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsHistoryModal.tsx, src/components/AdminDashboard/NotificationsDashboard/RecurringMeetings.tsx, src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/CreateNewMeeting.tsx, src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/index.tsx, src/components/AdminDashboard/NotificationsDashboard/UrgentMeetingRequests.tsx, src/components/AdminDashboard/NotificationsDashboard/index.tsx, src/components/ClientDashboard/EnrolledProgramSelectionScreen.tsx/UrgentMeetingRequestModal.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/index.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsTracking.tsx, src/components/ClientDashboard/HealthyHabits/index.tsx, src/components/Settings/AdminSettings.tsx, src/components/Settings/ClientSettings.tsx, src/components/emails/ScheduledMeetingEmail.tsx, src/server/api/emails/private-mutations.tsx, src/server/api/program-enrollments/queries.ts, src/server/api/scheduled-meetings/private-mutations.ts, src/server/api/scheduled-meetings/public-mutations.ts, src/server/api/scheduled-meetings/queries.ts, src/server/models/ScheduledMeeting.ts, src/server/models/index.ts, src/types/ScheduledMeeting.ts, src/types/index.ts, src/utils/constants/apiErrors.ts
=> feat: Let admins schedule meetings with clients

src/app/dashboard/client/get-preventative-screenings/page.tsx, src/components/AdminDashboard/ClientManagementDashboard/index.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsClientDashboard.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsMetrics.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/index.tsx, src/components/AdminDashboard/NotificationsDashboard/UrgentMeetingRequests.tsx, src/components/AdminDashboard/PendingApplicationDashboard/AcceptPendingApplicationButton.tsx, src/components/AdminDashboard/PendingApplicationDashboard/RejectPendingApplicationButton.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/components/AdminDashboard/Sidebar/CollapsibleSidebarButton.tsx, src/components/ClientDashboard/GetPreventativeScreenings/GetPreventativeScreeningsApply.tsx, src/components/ClientDashboard/GetPreventativeScreenings/GetPreventativeScreeningsInfo.tsx, src/components/ClientDashboard/GetPreventativeScreenings/index.tsx
Created blank tabs for Get Preventative Screenings. Added metrics tab and multiple status icons for Healthy Habits.
#141 
Just login as an admin and look at the Healthy Habits section of the dashboard. For Get Preventative Screenings, login as client enrolled to see the tabs, but there's nothing on the tabs.
=> feat: Start Get Preventative Screenings and Additions to Healthy Habits Metrics

.github/workflows/cache.yml
=> feat: Attempt to cache next build

.github/workflows/cache.yml
=> feat: Add env variables to main caching step

.github/workflows/cache.yml, .github/workflows/pr.yml
=> feat: Remove next build cache

src/components/AdminDashboard/ClientManagementDashboard/ClientProgramManagementForm/index.tsx
=> feat: Update client management message

src/app/dashboard/admin/programs/vaccine-voucher/page.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/index.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/RigsWithoutCigsMetric.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/index.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/VaccineVoucherDashboard.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/VaccineVoucherMetrics.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/index.tsx, src/server/api/program-enrollments/queries.ts
Added client and metrics tabs to the vaccine voucher admin programs page, similar to healthy habits. 
NA
login as admin and check the page. possibly remove/add users to vaccine voucher program to ensure the page is pulling the correct data for the table and metrics
=> feat: vaccine voucher admin dashboard programs page

src/components/AdminDashboard/AdminDashboardTable/index.tsx, src/components/AdminDashboard/AdminProgramDashboard/index.tsx, src/components/AdminDashboard/ClientManagementDashboard/index.tsx, src/components/AdminDashboard/DiabetesPreventionDashboard/DiabetesPreventionClientsDashboard.tsx, src/components/AdminDashboard/DiabetesPreventionDashboard/index.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/GetPreventativeScreeningsClientDashboard.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/ScreeningRequestManagementTable.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/index.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsClientDashboard.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/index.tsx, src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/CreateNewMeeting.tsx, src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/index.tsx, src/components/AdminDashboard/NotificationsDashboard/UrgentMeetingRequests.tsx, src/components/AdminDashboard/NotificationsDashboard/index.tsx, src/components/AdminDashboard/PendingApplicationDashboard/AcceptPendingApplicationButton.tsx, src/components/AdminDashboard/PendingApplicationDashboard/RejectPendingApplicationButton.tsx, src/components/AdminDashboard/PendingApplicationDashboard/index.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/RigsWithoutCigsClientDashboard.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/index.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/VaccineVoucherDashboard.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/index.tsx, src/components/ClientDashboard/ClientProgramDashboard/index.tsx, src/components/ClientDashboard/GetPreventativeScreenings/index.tsx, src/components/ClientDashboard/HealthyHabits/index.tsx, src/components/ClientDashboard/RigsWithoutCigs/index.tsx, src/components/ClientDashboard/VaccineVoucher/VaccineVoucherDashboard.tsx
=> feat: Abstract common views

src/components/ClientDashboard/RigsWithoutCigs/RigsWithoutCigsHistory/SubmittedFagerstromTestList/FagerstromTestModal.tsx, src/components/EnrollmentForm/GeneralInformationFormSection.tsx, src/components/EnrollmentForm/ProgramSelectionFormSection.tsx, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx, src/components/EnrollmentForm/QualifyingQuestionsFormSection.tsx, src/components/Modal/GenericModal.tsx, src/components/SCFModal/index.tsx, src/server/api/fagerstrom-tests/public-mutations.ts
Replaced a tags with link, added auth, replaced window.alert, and created generic modal component.
#154
=> feat: Polish app

src/components/AdminDashboard/ClientManagementDashboard/ClientProgramManagementForm/index.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/ScreeningRequestManagementTable.tsx, src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/CreateNewMeeting.tsx, src/components/AdminDashboard/PendingApplicationDashboard/AcceptPendingApplicationButton.tsx, src/components/AdminDashboard/PendingApplicationDashboard/PendingApplicationInfoModal/FormResponse.tsx, src/components/AdminDashboard/PendingApplicationDashboard/RejectPendingApplicationButton.tsx, src/components/ChangePassword/ChangePasswordForm.tsx, src/components/ClientDashboard/EnrolledProgramSelectionScreen.tsx/UrgentMeetingRequestModal.tsx, src/components/ClientDashboard/GetPreventativeScreenings/GetPreventativeScreeningsHistory/index.tsx, src/components/ClientDashboard/GetPreventativeScreenings/GetPreventativeScreeningsRequestForm.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/HealthyHabitsTrackingFormList/index.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsTracking.tsx, src/components/ClientDashboard/VaccineVoucher/VaccineVoucherApplyForm/VaccineVoucherApplyForm.tsx, src/components/ClientDashboard/VaccineVoucher/VaccineVoucherApplyForm/helpers.ts, src/components/EnrollmentForm/ProgramSpecificQuestions/ProgramSpecificQuestionsFormSection.tsx, src/components/ForgotPassword/ForgotPasswordForm.tsx, src/components/ForgotPassword/ResetPasswordForm.tsx, src/components/VerifyEmail/VerifyEmail.tsx, src/components/VerifyEmail/VerifyEmailSuccess.tsx
=> feat: Polish UI/UX

src/components/AdminDashboard/GetPreventativeScreeningsDashboard/GetPreventativeScreeningsMetrics.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/GetPreventativeScreeningsMetrics/YearlyTrendChart.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/GetPreventativeScreeningsMetrics/index.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/index.tsx
Added some more features to the gps metrics page like a graph and current month analysis
Closes #168 GPS Metrics
run pnpm dev with admin credentials and go to gps metrics tab
Side note - the legend is being difficult and on smaller screens it seeps into the graph. I've tried a lot to fix but nothing working with me
=> feat: GPS Metrics Additions

src/components/AdminDashboard/EnrollmentFormResponseModal/GeneralInformationResponses.tsx, src/components/AdminDashboard/EnrollmentFormResponseModal/ProgramSpecificResponses/RigsWithoutCigsResponses.tsx, src/components/AdminDashboard/EnrollmentFormResponseModal/QualifyingQuestionResponses.tsx
=> feat: Add missing fields to Enrollment Form Response Modal

src/app/api/users/actions/create-client-account/helpers.ts, src/app/api/users/actions/create-client-account/route.ts, src/components/ClientDashboard/ClientProgramDashboard/index.tsx, src/components/ClientDashboard/EnrolledProgramSelectionScreen.tsx/index.tsx, src/components/ClientDashboard/GetPreventativeScreenings/GetPreventativeScreeningsRequestForm.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/HealthyHabitsTrackingFormList/HealthyHabitsTrackingFormListItem.tsx, src/components/ClientDashboard/HealthyHabits/HealthyHabitsHistory/HealthyHabitsTrackingFormList/HealthyHabitsTrackingFormModal.tsx, src/components/ClientDashboard/RigsWithoutCigsAddInfo/index.tsx, src/server/api/enrollment-forms/public-mutations.ts, src/styles/theme.ts, src/types/EnrollmentForm/ProgramSpecificQuestionsSection.ts
=> feat: Add API to create clients without enrollment form

src/types/EnrollmentForm/ProgramSpecificQuestionsSection.ts
=> fix: Remove extra validation

src/components/AdminDashboard/AdminDashboardTable/index.tsx, src/components/AdminDashboard/DiabetesPreventionDashboard/DiabetesPreventionMetrics.tsx, src/components/AdminDashboard/GetPreventativeScreeningsDashboard/GetPreventativeScreeningsMetrics/index.tsx, src/components/AdminDashboard/HealthyHabitsDashboard/HealthyHabitsMetrics.tsx, src/components/AdminDashboard/MetricsTable/index.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/RigsWithoutCigsMetric.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/VaccineVoucherMetrics.tsx, src/components/AdminDashboard/VaccineVaccineDashboard/index.tsx
Added metrics similar to that of the GPS page, including totals, request per vaccine and totals per vaccine, and yearly charts
NA
Check metric numbers for multiple users, manipulating vaccine request status in DB to simulate changes
=> feat: Vaccine Voucher Metrics

src/app/api/users/actions/create-client-account/route.ts, src/components/AdminDashboard/RigsWithoutCigsDashboard/RigsWithoutCigsClientDashboard.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/RigsWithoutCigsMetric.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/UpdateStatusForm.tsx, src/components/AdminDashboard/RigsWithoutCigsDashboard/index.tsx, src/server/api/enrollment-forms/public-mutations.ts, src/server/models/User.ts, src/types/RigsWithoutCigsStatus.ts, src/types/User.ts
=> feat: Add rigs without cigs status field

src/app/api/users/actions/create-client-account/route.ts, src/components/AdminDashboard/ClientManagementDashboard/ClientProgramManagementForm/index.tsx, src/components/AdminDashboard/ClientManagementDashboard/index.tsx, src/components/ClientDashboard/GetPreventativeScreenings/helpers.ts, src/components/ClientDashboard/VaccineVoucher/VaccineVoucherApplyForm/VaccineVoucherApplyForm.tsx, src/components/Profile/ClientProfile/index.tsx, src/server/api/enrollment-forms/public-mutations.ts, src/server/models/User.ts, src/types/User.ts
Add additional fields to the client management from
#179
1. Login in as an admin
2. Modify a client
3. Save the results
4. Refresh the page
5. Verify changes were saved
**Double Check Validations on all fields**
=> feat: Add DOB and Goals to client managment form

.github/workflows/weekly-zoom-reminder.yml, .gitignore, .vscode/settings.json, scripts/.env, scripts/README.md, scripts/create_clients_from_csv.py, scripts/fake_clients.csv, scripts/requirements.txt, src/app/api/feature-flags/route.ts, src/app/api/users/actions/create-client-account/helpers.ts, src/app/api/users/actions/create-client-account/route.ts, src/app/dashboard/client/layout.tsx, src/app/update-client-information/page.tsx, src/components/AdminDashboard/AdminDashboardTable/index.tsx, src/components/ClientDashboard/UpdateClientInformation/index.tsx, src/middleware.ts, src/server/api/emails/helpers.ts, src/server/api/enrollment-forms/public-mutations.ts, src/server/api/feature-flags/private-mutations.ts, src/server/api/feature-flags/queries.ts, src/server/api/users/public-mutations.ts, src/server/models/FeatureFlag.ts, src/server/models/User.ts, src/server/models/index.ts, src/types/FeatureFlag.ts, src/types/User.ts, src/types/index.ts
=> feat: Add script to import clients without enrollment form

.github/workflows/pr.yml, .vscode/settings.json, src/utils/test2.ts
=> feat: Have knip comment on PRs

src/components/AdminDashboard/NotificationsDashboard/ScheduledMeetings/CreateNewMeeting.tsx, src/utils/serializeMongooseObject.ts
=> feat: Fix login flow

SCF.postman_collection.json
=> feat: Add postman collection

scripts/create_clients_from_csv.py, scripts/parse_file.py
=> feat: Update file parsing

src/app/api/emails/actions/send-daily-scheduled-meeting-reminders/route.ts, src/app/api/emails/actions/send-zoom-reminder-emails/route.ts, src/utils/constants/featureFlag.ts
=> feat: Add feature flag to ignore automatic jobs
